version: '3.8'

services:
   rebbitmq:
      image: rabbitmq:3-management
      ports:
         - '5672:5672' # RabbitMQ default port
         - '15672:15672' # RabbitMQ management UI
      # environment:
      # RABBITMQ_DEFAULT_USER: docker
      # RABBITMQ_DEFAULT_PASS: docker
      volumes:
         - rabbitmq_data:/var/lib/rabbitmq

volumes:
   rabbitmq_data:
