version: '3.8'

services:
   rebbitmq:
      image: rabbitmq:3-management
      ports:
         - '5672:5672' # RabbitMQ default port
         - '15672:15672' # RabbitMQ management UI
      # environment:
      # RABBITMQ_DEFAULT_USER: docker
      # RABBITMQ_DEFAULT_PASS: docker
      volumes:
         - rabbitmq_data:/var/lib/rabbitmq

   jeager:
      image: jaegertracing/all-in-one:1.57
      ports:
         - '16686:16686' # Jaeger UI
         - '6831:6831/udp' # Traces UDP
         - '14268:14268' # Traces HTTP
         - '4317:4317' # gRPC endpoint
         - '4318:4318' # Http endpoint

   kong-api-gateway:
      image: kong:3.9
      environment:
         KONG_DATABASE: off
         KONG_ADMIN_LISTEN: '0.0.0.0:8001'
         KONG_ADMIN_GUI_URL: 'http://localhost:8002'
         KONG_DECLARATIVE_CONFIG: '/kong/config.yml'
      extra_hosts:
         - 'host.docker.internal:host-gateway' # localhost pra ele é meu pc agora nao o localhost dentro do container
      volumes:
         - './docker/kong/config.yml:/kong/config.yml'
      ports:
         - '8000:8000' # Proxy (API)
         - '8001:8001' # Admin API
         - '8002:8002' # UI Admin
         - '8443:8443' # Proxy (API) HTTPS
         - '8444:8444' # (API) Admin HTTPS

volumes:
   rabbitmq_data:
